### ISSUE TITLE
Virtual pc uses several deprecated functions.

### ISSUE THREAD

**Issue by abgreeve** [evltuma/moodle-mod_virtualpc#1]
The virtual pc mod uses several deprecated functions which show notices / errors when navigating around. These are:
add_intro_editor - deprecated since 2.9
add_to_log - deprecated since 2.7
error - deprecated since 2.0
The error messages that these show include suggestions on what to use instead.

**Comment by agtdino** [comment]
Regards,

Thanks for testing the virtualpc module, we have corrected the deprecated functions and have published a new version of the module for each branch of moodle.
