### ISSUE TITLE
Invalid syntax in the lang files

### ISSUE THREAD

**Issue by mudrd8mz** [evltuma/moodle-mod_virtualpc#2]
The concatenation used at https://github.com/evltuma/moodle-mod_virtualpc/blob/master/lang/en/virtualpc.php#L35 is a valid PHP, but yet the Moodle string files should not use such statements. Please refer to https://docs.moodle.org/dev/Plugin_contribution_checklist#Strings

As a consequences, the plugin can't be registered with AMOS (lang.moodle.org) unless this is fixed.

**Comment by agtdino** [comment]
Thank you for your comment, I've push new version with out this concatenated string.
